#!/bin/bash
# Script of step 6: Processing - INDEL Call
# Goal: process BAM file - filter indels in fileVcf in reference to fileFasta
# Tool: GATK (SelectVariants)

fileFasta=$1
fileVcf=$2
fileResult=$3
fileCheck=$4

(java -jar $GATK -T SelectVariants -R "$fileFasta" -V "$fileVcf" -selectType INDEL -selectType mixed -o "$fileResult") 2> "$fileCheck"

exit 0
